//  import img1 from "../../assets"
import img1 from "../../assets/images/alexunder-hess-bWZAPKm0zZE-unsplash.jpg";
import img2 from "../../assets/images/alexunder-hess-6zqd6092B1c-unsplash.jpg";
import shortid from "shortid";
export const sectionFourData = [
    {
        col: "col-md-4 col-sm-6 col-lg-2 ",
        brand: "havells",
        title: "kids headphones bulk 10 back multi colored for ...",
        price: "$99.00",
        value: 3,
        logo1: img1,
        logo2: img2,
        id: shortid.generate(),
        type: "watch",
        category: "watches",
        tag: [
            {
                kind1: "watches",
                kind2: "smart watches",
                kind3: "sports watches",
                kind4: "classic watches",
                kind5: "smart band",
            },
        ],
        availability: "in stock",
        quantity: "22 items",
    },
    {
        col: "col-md-4 col-sm-6 col-lg-2 ",
        brand: "havells",
        title: "kids headphones bulk 10 back multi colored for ...",
        price: "$99.00",
        value: 3,
        logo1: img1,
        logo2: img2,
        id: shortid.generate(),
        type: "watch",
        category: "watches",
        tag: [
            {
                kind1: "watches",
                kind2: "smart watches",
                kind3: "sports watches",
                kind4: "classic watches",
                kind5: "smart band",
            },
        ],
        availability: "in stock",
        quantity: "22 items",
    },
    {
        col: "col-md-4 col-sm-6 col-lg-2 ",
        brand: "havells",
        title: "kids headphones bulk 10 back multi colored for ...",
        price: "$99.00",
        value: 3,
        logo1: img1,
        logo2: img2,
        id: shortid.generate(),
        type: "watch",
        category: "watches",
        tag: [
            {
                kind1: "watches",
                kind2: "smart watches",
                kind3: "sports watches",
                kind4: "classic watches",
                kind5: "smart band",
            },
        ],
        availability: "in stock",
        quantity: "22 items",
    },
    {
        col: "col-md-4 col-sm-6 col-lg-2 ",
        brand: "havells",
        title: "kids headphones bulk 10 back multi colored for ...",
        price: "$99.00",
        value: 3,
        logo1: img1,
        logo2: img2,
        id: shortid.generate(),
        type: "watch",
        category: "watches",
        tag: [
            {
                kind1: "watches",
                kind2: "smart watches",
                kind3: "sports watches",
                kind4: "classic watches",
                kind5: "smart band",
            },
        ],
        availability: "in stock",
        quantity: "22 items",
    },
    {
        col: "col-md-4 col-sm-6 col-lg-2 ",
        brand: "havells",
        title: "kids headphones bulk 10 back multi colored for ...",
        price: "$99.00",
        value: 3,
        logo1: img1,
        logo2: img2,
        id: shortid.generate(),
        type: "watch",
        category: "watches",
        tag: [
            {
                kind1: "watches",
                kind2: "smart watches",
                kind3: "sports watches",
                kind4: "classic watches",
                kind5: "smart band",
            },
        ],
        availability: "in stock",
        quantity: "22 items",
    },
    {
        col: "col-md-4 col-sm-6 col-lg-2 ",
        brand: "havells",
        title: "kids headphones bulk 10 back multi colored for ...",
        price: "$99.00",
        value: 3,
        logo1: img1,
        logo2: img2,
        id: shortid.generate(),
        type: "watch",
        category: "watches",
        tag: [
            {
                kind1: "watches",
                kind2: "smart watches",
                kind3: "sports watches",
                kind4: "classic watches",
                kind5: "smart band",
            },
        ],
        availability: "in stock",
        quantity: "22 items",
    },
];
